spring.application.name=iniciacion

#Indicacion del puerto Tomcat (Falla al ir a la webss)
server.port=8081

#Conexion a la base de datos

spring.datasource.url = jdbc:h2:mem:testdb

#DESGLOSANDO LA URL BASE DE DATOS (Basado en sintaxis jdbc)
#jdbc -> Tecnologia utilizada
#h2 -> Motor de la base de datos
#mem -> que la memoria utilizada va a ser la ram
#testdb -> nombre de la base de datos virtual

spring.datasource.driverClassName=org.h2.Driver

#Es el driver encargado de traducir las ordenes javas a H2